version: '3.1'
services:
  wordpress:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: dev_wordpress_webserver
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./www/:/var/www/html
  db:
    image: mysql:5.6
    restart: unless-stopped
    container_name: dev_wordpress_dbserver
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - db:/var/lib/mysql
volumes:
  db: